### ISSUE TITLE
Failing to fetch deb while installing 

### ISSUE THREAD

**Issue by Guesh1337** [YunoHost-Apps/guacamole_ynh#20]
Hi ! trying to install Guac on my yunohost pi 8gb and it looks like it's not fetching the right .deb so it's erroring
Here is my logs

https://paste.yunohost.org/raw/urahuhodon

Thanks.

**Comment by yalh76** [comment]
closed by https://github.com/YunoHost-Apps/guacamole_ynh/pull/25
