### ISSUE TITLE
Installation impossible téléchargement .deb

### ISSUE THREAD

**Issue by nat1906** [YunoHost-Apps/guacamole_ynh#21]
### Décrivez le bug

L'installation de l'application Guacamole échoue, car l'ordinateur n'arrive pas à télécharger l’archive d'installation de tomcat9 (la version que le script télécharge n'est plus disponible sur le serveur).

### Contexte

- Matériel : *Mac Pro 2.1*
- Version de YunoHost : *4.3.6.2*
- J'ai accès à mon serveur : *par SSH | par l'administrateur web*
- Vous êtes dans un contexte particulier ou vous avez effectué des réglages particuliers sur votre instance de YunoHost ? *non*
- Utilisation, ou tentative d'installation de la version/branche du paquet : *1.4.0~ynh1*

### Étapes à reproduire

- Lancer l'installation de l'application

### Comportement attendu

Installation impossible

### Journaux

Les lignes présentant le bug sont les dernières :

https://paste.yunohost.org/raw/abevacohag

**Comment by gtrdblt** [comment]
J'ai la même erreur : 

2022-03-24 11:04:34,057: WARNING - https://ftp.debian.org/debian/pool/main/t/tomcat9/tomcat9_9.0.55-1_all.deb:
2022-03-24 11:04:34,058: WARNING - 2022-03-24 11:04:34 erreur 404 : Not Found.

**Comment by yalh76** [comment]
closed by #25
