### ISSUE TITLE
Apache Tomcat Issue

### ISSUE THREAD

**Issue by seedrick** [YunoHost-Apps/guacamole_ynh#27]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

Tomcat throwing a null pointer exception after update..

### Context

- Hardware:RPi4
- YunoHost version: 4.3.6.3
- I have access to my server: webadmin and ssh
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: 1.4.0

### Steps to reproduce

Upgrade Guac form webadmin

### Expected behavior

Be able to access guac webpage.

**Comment by MHWCT** [comment]
I have the same issue right now and get an error message "no files found for tomcat9.service"
