### ISSUE TITLE
No Files found for tomcat9.service

### ISSUE THREAD

**Issue by systemop7** [YunoHost-Apps/guacamole_ynh#34]
Hey,
recently I am trying to install guacamole in my self hosted server. i was facing some issues

###Issue :

`No Files found for tomcat9.service`
`head: can not open '/etc/ssl/certs/java/cacerts' for  reading: no such file or derectory`

![AVLgH47d1a](https://user-images.githubusercontent.com/119477169/206621480-d0985953-f9da-4f25-96b3-aa2fabe83b4c.jpg)

![26RGXK9m3f](https://user-images.githubusercontent.com/119477169/206621503-b2a2d4d7-312e-4a25-98ef-cedb2a5915e9.jpg)

Server info :-
OS : Debian 10 (64-bit)
Yunohost version : 11.0.10.2

How can i sove this issue?

**Comment by Salamandar** [comment]
Fixed.
