### ISSUE TITLE
Guacamole 1.5.2 is not available .

### ISSUE THREAD

**Issue by julienhel61250** [YunoHost-Apps/guacamole_ynh#40]
Hello,

Guacamole 1.5.2 is not available .

https://downloads.apache.org/guacamole/

https://downloads.apache.org/guacamole/1.5.2/source/guacamole-server-1.5.2.tar.gz:
2023-12-12 23:23:30 ERROR 404: Not Found.

**Comment by thomas-jardinet** [comment]
Same. File has been deleted, 1.5.3 & 1.5.4 are available.

**Comment by RELTIN** [comment]
how to install the new version?

**Comment by RELTIN** [comment]
and versions 1.5.3 & 1.5.4 also give a 404 error

**Comment by enamaryn** [comment]
> and versions 1.5.3 & 1.5.4 also give a 404 error

With command line : sudo yunohost app upgrade guacamole ??

**Comment by RELTIN** [comment]
Guacamole is not found in the list of installed applications and guacamole cannot be installed due to the error above :(
![Снимок](https://github.com/YunoHost-Apps/guacamole_ynh/assets/90633589/c54dcc48-32e7-4ac2-9a61-4307ab2fb3d1)
